name: jupyterlab-metadata-service

channels:
- conda-forge

dependencies:
- aiohttp
- jupyterlab_server >=0.2,<0.3
- nodejs >8,<9
- notebook >=4.3.1
- python >=3.6,<3.7
- pip:
  - jupyter-server-proxy
