name: jupyterlab-metadata-service

channels:
- conda-forge

dependencies:
- python >=3.7,<3.8
- notebook >=4.3.1
- jupyterlab_server >=0.2,<0.3
- nodejs >8,<9
- aiohttp
- pip:
  - jupyter-server-proxy
