#!/usr/bin/env bash
set -ex

LAB_HEAD=v1.0.0a1
COMMENTING_HEAD=binder

echo "CONDA_PREFIX is $CONDA_PREFIX"

if [ "${NB_UID}not-on-binder" = "not-on-binder" ]; then
  echo "...and that's fine"
else
  if [ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]; then
    echo "...and we set it to ${CONDA_DIR}"
    export CONDA_PREFIX=$CONDA_DIR
  else
    echo "...and that's fine"
  fi
fi
conda env update -p ${CONDA_PREFIX} --file environment-dev.yml
conda clean -qtipsy

git clone https://github.com/jupyterlab/jupyterlab
git clone https://github.com/bollwyvl/jupyterlab-commenting

pushd jupyterlab
git checkout -f $LAB_HEAD
python -m pip install -e . --no-deps --ignore-installed
jupyter serverextension enable jupyterlab --sys-prefix
popd

pushd backend
python -m pip install -e . --no-deps --ignore-installed
jupyter serverextension enable jupyterlab_metadata_service_server --sys-prefix
popd

pushd backend/jupyterlab_metadata_service_server
jlpm
jlpm build
rm -rf node_modules
popd

pushd jupyterlab-commenting
git checkout -f $COMMENTING_HEAD
popd

pushd jupyterlab
jlpm run add:sibling ../frontend
jlpm run add:sibling ../jupyterlab-commenting
jlpm build
rm -rf $CONDA_PREFIX/share/jupyter/lab
mkdir -p $CONDA_PREFIX/share/jupyter/lab
cp -r dev_mode/{static,schemas,themes} $CONDA_PREFIX/share/jupyter/lab/
popd
